require: rubocop-rspec

RSpec/AlignLeftLetBrace:
  Enabled: true
RSpec/AlignRightLetBrace:
  Enabled: false
RSpec/AnyInstance:
  Enabled: true
RSpec/AroundBlock:
  Enabled: true
RSpec/BeEql:
  Enabled: true
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ContextWording:
  Enabled: true
RSpec/DescribeMethod:
  Enabled: true
RSpec/DescribeSymbol:
  Enabled: true
RSpec/DescribedClass:
  EnforcedStyle: described_class
RSpec/EmptyExampleGroup:
  Enabled: true
RSpec/EmptyLineAfterFinalLet:
  Enabled: true
RSpec/EmptyLineAfterSubject:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/ExampleWithoutDescription:
  Enabled: true
RSpec/ExampleWording:
  Enabled: true
RSpec/ExpectActual:
  Enabled: true
RSpec/ExpectChange:
  EnforcedStyle: method_call
RSpec/ExpectInHook:
  Enabled: true
RSpec/ExpectOutput:
  Enabled: true
RSpec/FilePath:
  Enabled: true
RSpec/Focus:
  Enabled: true
RSpec/HookArgument:
  EnforcedStyle: implicit
RSpec/InstanceSpy:
  Enabled: true
RSpec/InstanceVariable:
  Enabled: true
RSpec/InvalidPredicateMatcher:
  Enabled: true
RSpec/ItBehavesLike:
  EnforcedStyle: it_behaves_like
RSpec/IteratedExpectation:
  Enabled: false
RSpec/LeadingSubject:
  Enabled: true
RSpec/LetBeforeExamples:
  Enabled: true
RSpec/LetSetup:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MessageExpectation:
  EnforcedStyle: expect
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleDescribes:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 10
  Exclude:
    - 'spec/requests/**/*_spec.rb'
    - 'spec/features/**/*_spec.rb'
    - 'spec/system/**/*_spec.rb'
RSpec/MultipleSubjects:
  Enabled: true
RSpec/NamedSubject:
  Enabled: false
# RSpec/NestedGroups:
#   Enabled: TODO
RSpec/NotToNot:
  Enabled: true
RSpec/OverwritingSetup:
  Enabled: true
RSpec/RepeatedDescription:
  Enabled: true
RSpec/RepeatedExample:
  Enabled: true
RSpec/ReturnFromStub:
  Enabled: true
RSpec/ScatteredLet:
  Enabled: true
RSpec/ScatteredSetup:
  Enabled: true
RSpec/SharedContext:
  Enabled: true
RSpec/SingleArgumentMessageChain:
  Enabled: false
RSpec/SubjectStub:
  Enabled: true
RSpec/VerifiedDoubles:
  Enabled: true
RSpec/VoidExpect:
  Enabled: true
